#
# Copyright 2025-2026 Scott Gigawatt
#
# Licensed under the Apache License, Version 2.0.
#
# .yamllint.yaml: Enforce the shared two-space YAML style.
#

extends: default
rules:
  document-start: disable
  indentation:
    spaces: 2
    indent-sequences: true
  line-length: disable
  truthy: disable
